export default interface IEvolizAPISupplier {
    supplierid: number;
    userid: number;
    code: string;
    name: string;
    legalform: string;
    business_number: string;
    activity_number: string;
    vat_number: string;
    bank_information: {
        bank_account_detail: string;
        iban: string;
        bank_identification_code: string;
    };
    address: {
        addr: string;
        addr2: string;
        postcode: string;
        town: string;
        country: {
            label: string;
            iso2: string;
        };
    };
    phone: string;
    mobile: string;
    fax: string;
    website: string;
    comment: string;
    enabled: boolean;
    custom_fields: {
        custom_field_api: {
            label: string;
            value: string;
        };
        custom_field_api2: {
            label: string;
            value: string;
        };
    };
    default_values: {
        payterm: {
            paytermid: number;
            label: string;
        };
        paytype: {
            paytypeid: number;
            label: string;
        };
        analytic: {
            id: number;
            code: string;
            label: string;
            enabled: boolean;
        };
    };
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Supplier-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "supplierid": 9876,
//         "userid": 3780,
//             "code": "F160",
//                 "name": "Triiptic",
//                     "legalform": "SAS",
//                         "business_number": "123 456 789 12345",
//                             "activity_number": "1234A",
//                                 "vat_number": "FR20123456789",
//                                     "bank_information": {
//         "bank_account_detail": "12345 6789 012345678901 34",
//             "iban": "FR00 1234 5678 9012 3456 7890 134",
//                 "bank_identification_code": "ABCDEFGH"
//     },
//     "address": {
//         "addr": "176 avenue Joseph Louis Lambot",
//             "addr2": "Etage 2",
//                 "postcode": "83130",
//                     "town": "La Garde",
//                         "country": {
//             "label": "France",
//                 "iso2": "FR"
//         }
//     },
//     "phone": "01 46 72 50 04",
//         "mobile": "+33600000000",
//             "fax": "+33400000000",
//                 "website": "https://www.triiptic.fr",
//                     "comment": "Ce fournisseur est génial",
//                         "enabled": true,
//                             "custom_fields": {
//         "custom_field_api": {
//             "label": "label1",
//                 "value": "value1"
//         },
//         "custom_field_api2": {
//             "label": "label2",
//                 "value": "value2"
//         }
//     },
//     "default_values": {
//         "payterm": {
//             "paytermid": 3,
//                 "label": "15 jours"
//         },
//         "paytype": {
//             "paytypeid": 3,
//                 "label": "Carte bancaire"
//         },
//         "analytic": {
//             "id": 12345,
//                 "code": "ANA3",
//                     "label": "Axe analytique 3",
//                         "enabled": false
//         }
//     }
// }