export default interface IEvolizAPISupplierCredit {
    supplier_creditid: number;
    document_number: string;
    supplier: {
        supplierid: number;
        code: string;
        name: string;
    };
    default_currency: {
        code: string;
        conversion: number;
        symbol: string;
    };
    total: {
        vat_exclude: number;
        vat: number;
        vat_include: number;
    };
    status_code: number;
    status: string;
    status_dates: {
        create: string;
        paid: any;
        match: any;
    };
    locked: any;
    lockdate: any;
    documentdate: string;
    duedate: string;
    term: {
        paytype: {
            paytypeid: number;
            label: string;
        };
        payterm: {
            paytermid: number;
            label: string;
        };
    };
    comment: string;
    label: string;
    external_document_number: string;
    enabled: boolean;
    analytic: any;
    input_mode: string;
    file: string;
    webdoc: string;
    items: [{
        itemid: number;
        total: {
            vat_exclude: number;
            vat: any;
        };
        purchase_classification: {
            id: number;
            code: string;
            label: string;
        };
    }];
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Supplier-credit-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "supplier_creditid": 26263,
//         "document_number": "AF-20200200001",
//             "supplier": {
//         "supplierid": 45369,
//             "code": "F160",
//                 "name": "Triiptic"
//     },
//     "default_currency": {
//         "code": "EUR",
//             "conversion": 1,
//                 "symbol": "€"
//     },
//     "total": {
//         "vat_exclude": 324,
//             "vat": 64.8,
//                 "vat_include": 388.8
//     },
//     "status_code": 2,
//         "status": "create",
//             "status_dates": {
//         "create": "2020-01-15T18:00:00.000000Z",
//             "paid": null,
//                 "match": null
//     },
//     "locked": null,
//         "lockdate": null,
//             "documentdate": "2019-12-14",
//                 "duedate": "2019-12-14",
//                     "term": {
//         "paytype": {
//             "paytypeid": 3,
//                 "label": "Carte bancaire"
//         },
//         "payterm": {
//             "paytermid": 3,
//                 "label": "15 jours"
//         }
//     },
//     "comment": "",
//         "label": "Triiptic\r\nEtudes et prestations de service",
//             "external_document_number": "F-20190000160",
//                 "enabled": true,
//                     "analytic": null,
//                         "input_mode": "vat_exclude",
//                             "file": "https://../files/supplier-credit/26263",
//                                 "webdoc": "https://.../modules/webdoc/AMDKOED5NATQJGE21886-9ccce0c003319d10d2e94af0c75977ed",
//                                     "items": {
//         "itemid": 3569176,
//             "total": {
//             "vat_exclude": 324,
//                 "vat": null
//         },
//         "purchase_classification": {
//             "id": 68049,
//                 "code": "02",
//                     "label": "Etudes et prestations de service"
//         }
//     }
// }