export default interface IEvolizAPIBuy {
    buyid: number;
    userid: number;
    document_number: string;
    supplier: {
        supplierid: number;
        code: string;
        name: string;
    };
    default_currency: {
        code: string;
        conversion: number;
        symbol: string;
    };
    total: {
        vat_exclude: number;
        vat: number;
        vat_include: number;
        paid: number;
        net_to_pay: number;
    };
    status_code: number;
    status: string;
    status_dates: {
        create: string;
        prepare: string;
        voucher: string;
        inpayment: string;
        paid: string;
        match: string;
    };
    locked: boolean;
    lockdate: string;
    documentdate: string;
    duedate: string;
    term: {
        paytype: {
            paytypeid: number;
            label: string;
        };
        payterm: {
            paytermid: number;
            label: string;
        };
    };
    comment: string;
    label: string;
    external_document_number: string;
    enabled: boolean;
    analytic: any;
    input_mode: string;
    client: any;
    billable: boolean;
    startdate: string;
    enddate: string;
    cashentry: {
        entryid: number;
        date: string;
        cash: {
            id: number;
            label: string;
        }
    };
    file: string;
    links: string;
    webdoc: string;
    items: [{
        itemid: number;
        total: {
            vat_exclude: number;
            vat: number;
        };
        purchase_classification: {
            id: number;
            code: string;
            label: string;
        }
    }];
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Buy-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "buyid": 2361910,
//         "userid": 3780,
//             "document_number": "HA-20200002348",
//                 "supplier": {
//         "supplierid": 45369,
//             "code": "F160",
//                 "name": "Triiptic"
//     },
//     "default_currency": {
//         "code": "EUR",
//             "conversion": 1,
//                 "symbol": "€"
//     },
//     "total": {
//         "vat_exclude": 324,
//             "vat": 64.8,
//                 "vat_include": 388.8,
//                     "paid": 0,
//                         "net_to_pay": 388.8
//     },
//     "status_code": 2,
//         "status": "create",
//             "status_dates": {
//         "create": "2019-10-15T17:45:00.000000Z",
//             "prepare": "2019-11-17T14:25:00.000000Z",
//                 "voucher": null,
//                     "inpayment": null,
//                         "paid": null,
//                             "match": null
//     },
//     "locked": null,
//         "lockdate": null,
//             "documentdate": "2019-10-10",
//                 "duedate": "2019-10-25",
//                     "term": {
//         "paytype": {
//             "paytypeid": 3,
//                 "label": "Carte bancaire"
//         },
//         "payterm": {
//             "paytermid": 3,
//                 "label": "15 jours"
//         }
//     },
//     "comment": "",
//         "label": "Triiptic\r\nEtudes et prestations de service",
//             "external_document_number": "F-20190000160",
//                 "enabled": true,
//                     "analytic": null,
//                         "input_mode": "vat_exclude",
//                             "client": null,
//                                 "billable": false,
//                                     "startdate": null,
//                                         "enddate": null,
//                                             "cashentry": {
//         "entryid": 25,
//             "date": "22-09-2022",
//                 "cash": {
//             "id": 75,
//                 "label": "Caisse Toulon"
//         }
//     },
//     "file": "https://../files/buy/2361910",
//         "links": "https://../links/buy/2361910",
//             "webdoc": "https://.../modules/webdoc/9MDKOED5NATQJGE21886-9ccce0c003319d10d2e94af0c75977ed",
//                 "items": {
//         "itemid": 3569175,
//             "total": {
//             "vat_exclude": 324,
//                 "vat": null
//         },
//         "purchase_classification": {
//             "id": 68049,
//                 "code": "02",
//                     "label": "Etudes et prestations de service"
//         }
//     }
// }