export default interface IEvolizAPIArticle {
    articleid: number;
    userid: number;
    reference: string;
    reference_clean: string;
    nature: string;
    sale_classification: {
        id: number;
        code: number;
        label: string;
    };
    designation: string;
    designation_clean: string;
    quantity: number;
    weight: number;
    unit: string;
    unit_price_vat_exclude: number;
    unit_price_vat_include: number;
    vat: number;
    ttc: boolean;
    purchase_classification: {
        id: number;
        code: number;
        label: string;
    };
    margin: {
        purchase_unit_price_vat_exclude: number;
        coefficient: number;
        margin_percent: number;
        markup_percent: number;
        amount: number;
    };
    supplier: {
        supplierid: number;
        code: string;
        name: string;
    };
    supplier_reference: string;
    supplier_reference_clean: string;
    stock_management: boolean;
    stocked_quantity: number;
    enabled: boolean;
    picture_link: string;
    custom_fields: {
        custom_field_api: {
            label: string;
            value: string;
        };
        custom_field_api2: {
            label: string;
            value: string;
        };
    };
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Article-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "articleid": 12345,
//         "userid": 3780,
//             "reference": "SPLIT",
//                 "reference_clean": "SPLIT",
//                     "nature": "product",
//                         "sale_classification": {
//         "id": 45732,
//             "code": 4,
//                 "label": "Vente de marchandise"
//     },
//     "designation": "Banana Split <br />\nPour une durée de 12 mois",
//         "designation_clean": "Banana Split\nPour une durée de 12 mois",
//             "quantity": 12,
//                 "weight": 152.123,
//                     "unit": "M",
//                         "unit_price_vat_exclude": 30,
//                             "unit_price_vat_include": 36,
//                                 "vat": 20,
//                                     "ttc": false,
//                                         "purchase_classification": {
//         "id": 45732,
//             "code": 4,
//                 "label": "Achat de marchandise"
//     },
//     "margin": {
//         "purchase_unit_price_vat_exclude": 16,
//             "coefficient": 3.6,
//                 "margin_percent": 87.5,
//                     "markup_percent": 46.67,
//                         "amount": 20
//     },
//     "supplier": {
//         "supplierid": 9876,
//             "code": "C00123",
//                 "name": "Triiptic"
//     },
//     "supplier_reference": "SPLIT",
//         "supplier_reference_clean": "SPLIT",
//             "stock_management": true,
//                 "stocked_quantity": 5,
//                     "enabled": true,
//                         "picture_link": "https://../files/article/12345",
//                             "custom_fields": {
//         "custom_field_api": {
//             "label": "label1",
//                 "value": "value1"
//         },
//         "custom_field_api2": {
//             "label": "label2",
//                 "value": "value2"
//         }
//     }
// }