# sh ./bin/docker_up.sh --dev

version: '3.5'

x-env:
    &env
    PORT: 3000
    NODE_OPTIONS: "--max-old-space-size=4096"
    NODE_ENV: "DEVPSA_MDU"
    NODE_INSTALL: "true"

services:
    oswedev_back:
        user: ${USER_UID}
        command: sh -c "/home/node/oswedev/bin/entrypoint.sh && yarn tsc-watch"
        container_name: oswedev_server_container
        environment:
            <<: *env
        ports:
            - '3050-3055:3000' # depend on if we use load balancer
