export default interface IEvolizAPISalesClassification {
    classificationid: number;
    code: string;
    label: string;
    account: {
        accountid: number;
        code: string;
        label: string;
    };
    enabled: boolean;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Sale-classification-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "classificationid": 5670,
//         "code": "01",
//             "label": "Table et chaise",
//                 "account": {
//         "accountid": 6099,
//             "code": "707",
//                 "label": "Ventes de marchandises"
//     },
//     "enabled": true
// }