export default interface IEvolizAPIPaymentTypes {
    paytypeid: number;
    label: string;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Payment-types-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "paytypeid": 3,
//         "label": "Carte bancaire"
// }