export default interface IEvolizAPIUnitCodes {
    unitcodeid: number;
    unitcode: string;
    label: string;
    symbol: string;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#tag/Unit-codes (v1.24 in https://evoliz.io/changelog)):
// {
//     "unitcodeid": 1,
//         "unitcode": "G",
//             "label": "Gramme",
//                 "symbol": "g"
// }