export default interface IEvolizAPIVatRates {
    vatid: number;
    rate: number;
    account: {
        accountid: number;
        code: string;
        label: string;
    };
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Vat-rates-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "vatid": 13,
//         "rate": 10,
//             "account": {
//         "accountid": 45,
//             "code": "6061",
//                 "label": "Fournitures non stockables"
//     }
// }