export default interface IEvolizAPIAccounts {
    accountid: number;
    code: string;
    label: string;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Accounts-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "accountid": 45,
//         "code": "6061",
//             "label": "Fournitures non stockables"
// }