export default interface IEvolizAPIAnalytic {
    id: number;
    code: string;
    label: string;
    enabled: boolean;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Analytic-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "id": 12345,
//         "code": "ANA3",
//             "label": "Axe analytique 3",
//                 "enabled": false
// }