export default interface IEvolizAPIPaymentTerms {
    paytermid: number;
    label: string;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Payment-terms-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "paytermid": 3,
//         "label": "15 jours"
// }