export default interface IEvolizAPIEvents {
    eventid: number;
    userid: number;
    action: string;
    linked_element: {
        type: string;
        id: number;
        info: string;
        link: string;
    };
    stampdate: string;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Event-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "eventid": 105614026,
//         "userid": 3780,
//             "action": "create",
//                 "linked_element": {
//         "type": "INVOICE",
//             "id": 2476128,
//                 "info": "F-20190000160",
//                     "link": "https://.../invoices/2476128"
//     },
//     "stampdate": "2019-10-10T09:26:39.000000Z"
// }