export default interface IEvolizAPIPurchasesClassification {
    classificationid: number;
    code: string;
    label: string;
    account: {
        accountid: number;
        code: string;
        label: string;
    };
    vataccount: {
        accountid: number;
        code: string;
        label: string;
    };
    rate: number;
    enabled: boolean;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Purchases-classification-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "classificationid": 34597,
//         "code": "06",
//             "label": "Fuel",
//                 "account": {
//         "accountid": 45,
//             "code": "6061",
//                 "label": "Fournitures non stockables"
//     },
//     "vataccount": {
//         "accountid": 44,
//             "code": "44566",
//                 "label": "TVA sur autres biens et services"
//     },
//     "rate": 0,
//         "enabled": true
// }