export default interface IEvolizAPIPurchasesAffectation {
    affectationid: number;
    code: string;
    label: string;
    account: {
        accountid: number;
        code: string;
        label: string;
    };
    enabled: boolean;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Purchases-affectation-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "affectationid": 5670,
//         "code": "FR-BANK",
//             "label": "Frais bancaire",
//                 "account": {
//         "accountid": 45,
//             "code": "6061",
//                 "label": "Fournitures non stockables"
//     },
//     "enabled": true
// }