export default interface IEvolizAPIProspect {
    prospectid: number;
    userid: number;
    name: string;
    business_number: string;
    activity_number: string;
    vat_number: string;
    address: {
        addr: string;
        addr2: string;
        postcode: string;
        town: string;
        country: {
            label: string;
            iso2: string;
        }
    };
    phone: string;
    mobile: string;
    fax: string;
    website: string;
    comment: string;
    enabled: boolean;
    custom_fields: {
        custom_field_api: {
            label: string;
            value: string;
        };
        custom_field_api2: {
            label: string;
            value: string;
        }
    };
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#tag/Prospect (v1.24 in https://evoliz.io/changelog)):
// {
//     "prospectid": 12345,
//         "userid": 24377,
//             "name": "Triiptic",
//                 "business_number": "123 456 789 12345",
//                     "activity_number": "1234A",
//                         "vat_number": "FR20123456789",
//                             "address": {
//         "addr": "176 avenue Joseph Louis Lambot",
//             "addr2": "Etage 2",
//                 "postcode": "83130",
//                     "town": "La Garde",
//                         "country": {
//             "label": "France",
//                 "iso2": "FR"
//         }
//     },
//     "phone": "01 46 72 50 04",
//         "mobile": "+33600000000",
//             "fax": "+33400000000",
//                 "website": "https://www.triiptic.fr",
//                     "comment": "Ce prospect est génial",
//                         "enabled": true,
//                             "custom_fields": {
//         "custom_field_api": {
//             "label": "label1",
//                 "value": "value1"
//         },
//         "custom_field_api2": {
//             "label": "label2",
//                 "value": "value2"
//         }
//     }
// }