export default interface IEvolizAPIClient {
    clientid: number;
    userid: number;
    code: string;
    civility: string;
    name: string;
    type: string;
    legalform: string;
    business_number: string;
    activity_number: string;
    vat_number: string;
    immat_number: string;
    bank_information: {
        bank_name: string;
        bank_account_detail: string;
        iban: string;
        bank_identification_code: string;
    };
    address: {
        addr: string;
        addr2: string;
        postcode: string;
        town: string;
        country: {
            label: string;
            iso2: string;
        }
    };
    delivery_address: {
        addr: string;
        addr2: string;
        postcode: string;
        town: string;
        country: {
            label: string;
            iso2: string;
        }
    };
    phone: string;
    mobile: string;
    fax: string;
    website: string;
    safe_amount: number;
    term: {
        validity: number;
        payterm: {
            paytermid: number;
            label: string;
        };
        paytype: {
            paytypeid: number;
            label: string;
        };
        vat_rate: number;
        rebate_percent: number;
        analytic: {
            id: number;
            code: string;
            label: string;
            enabled: boolean;
        };
        vat_exoneration: any;
        vat_exoneration_other_reason: string;
        penalty: number;
        nopenalty: boolean;
        recovery_indemnity: boolean;
        discount_term: number;
        no_discount_term: boolean;
    };
    ttc: boolean;
    comment: string;
    enabled: boolean;
    custom_fields: {
        custom_field_api: {
            label: string;
            value: string;
        };
        custom_field_api2: {
            label: string;
            value: string;
        };
    };
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Client-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "clientid": 9876,
//         "userid": 3780,
//             "code": "C00123",
//                 "civility": "M.",
//                     "name": "Triiptic",
//                         "type": "Professionnel",
//                             "legalform": "SAS",
//                                 "business_number": "123 456 789 12345",
//                                     "activity_number": "1234A",
//                                         "vat_number": "FR20123456789",
//                                             "immat_number": "RCS PARIS 12345678912345",
//                                                 "bank_information": {
//         "bank_name": "Banque Populaire",
//             "bank_account_detail": "12345 6789 012345678901 34",
//                 "iban": "FR00 1234 5678 9012 3456 7890 134",
//                     "bank_identification_code": "ABCDEFGH"
//     },
//     "address": {
//         "addr": "176 avenue Joseph Louis Lambot",
//             "addr2": "Etage 2",
//                 "postcode": "83130",
//                     "town": "La Garde",
//                         "country": {
//             "label": "France",
//                 "iso2": "FR"
//         }
//     },
//     "delivery_address": {
//         "addr": "129 rue Servient",
//             "addr2": "Etage 15",
//                 "postcode": "69003",
//                     "town": "Lyon",
//                         "country": {
//             "label": "France",
//                 "iso2": "FR"
//         }
//     },
//     "phone": "01 46 72 50 04",
//         "mobile": "+33600000000",
//             "fax": "+33400000000",
//                 "website": "https://www.triiptic.fr",
//                     "safe_amount": 4000,
//                         "term": {
//         "validity": 0,
//             "payterm": {
//             "paytermid": 3,
//                 "label": "15 jours"
//         },
//         "paytype": {
//             "paytypeid": 3,
//                 "label": "Carte bancaire"
//         },
//         "vat_rate": 20,
//             "rebate_percent": 12,
//                 "analytic": {
//             "id": 12345,
//                 "code": "ANA3",
//                     "label": "Axe analytique 3",
//                         "enabled": false
//         },
//         "vat_exoneration": null,
//             "vat_exoneration_other_reason": "My custom vat exoneration reason",
//                 "penalty": 3,
//                     "nopenalty": false,
//                         "recovery_indemnity": false,
//                             "discount_term": 0,
//                                 "no_discount_term": false
//     },
//     "ttc": false,
//         "comment": "Ce client est génial",
//             "enabled": true,
//                 "custom_fields": {
//         "custom_field_api": {
//             "label": "label1",
//                 "value": "value1"
//         },
//         "custom_field_api2": {
//             "label": "label2",
//                 "value": "value2"
//         }
//     }
// }