export default interface IEvolizAPIContactClient {
    contactid: number;
    userid: number;
    client: {
        clientid: number;
        code: string;
        civility: string;
        name: string;
        type: string;
        legalform: string;
        business_number: string;
        activity_number: string;
        vat_number: string;
        immat_number: string;
        bank_information: {
            bank_name: string;
            bank_account_detail: string;
            iban: string;
            bank_identification_code: string;
        };
        address: {
            addr: string;
            addr2: string;
            postcode: string;
            town: string;
            country: {
                label: string;
                iso2: string;
            };
        };
        delivery_address: {
            addr: string;
            addr2: string;
            postcode: string;
            town: string;
            country: {
                label: string;
                iso2: string;
            };
        };
        phone: string;
        mobile: string;
        fax: string;
        website: string;
        safe_amount: number;
        term: {
            validity: number;
            payterm: {
                paytermid: number;
                label: string;
            };
            paytype: {
                paytypeid: number;
                label: string;
            };
            vat_rate: number;
            rebate_percent: number;
            analytic: {
                id: number;
                code: string;
                label: string;
                enabled: boolean;
            };
            vat_exoneration: any;
            vat_exoneration_other_reason: string;
            penalty: number;
            nopenalty: boolean;
            recovery_indemnity: boolean;
            discount_term: number;
            no_discount_term: boolean;
        };
        ttc: boolean;
        comment: string;
        enabled: boolean;
        custom_fields: {
            custom_field_api: {
                label: string;
                value: string;
            };
            custom_field_api2: {
                label: string;
                value: string;
            };
        };
    };
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Contact-Client-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "contactid": 8568,
//         "userid": 3780,
//             "client": {
//         "clientid": 9876,
//             "code": "C00123",
//                 "name": "Triiptic",
//                     "civility": "M.",
//                         "contact": {
//             "contactid": 45,
//                 "firstname": "Olivier",
//                     "lastname": "Gasquet",
//                         "email": "contact@triiptic.fr"
//         }
//     },
//     "civility": "Monsieur",
//         "lastname": "Gasquet",
//             "firstname": "Olivier",
//                 "email": "contact@triiptic.fr",
//                     "profil": "CTO",
//                         "label_tel_primary": "Tél bureau",
//                             "tel_primary": "01 46 72 50 04",
//                                 "label_tel_secondary": "Portable",
//                                     "tel_secondary": "+33600000000",
//                                         "label_tel_tertiary": "Télécopie (bureau)",
//                                             "tel_tertiary": "0900000000",
//                                                 "enabled": true,
//                                                     "consent": "without",
//                                                         "favorite": false,
//                                                             "custom_fields": {
//         "custom_field_api": {
//             "label": "label1",
//                 "value": "value1"
//         },
//         "custom_field_api2": {
//             "label": "label2",
//                 "value": "value2"
//         }
//     }
// }