export default interface IEvolizAPIContactProspect {
    contactid: number;
    userid: number;
    prospect: {
        prospectid: number;
        code: string;
        name: string;
        contact: {
            contactid: number;
            firstname: string;
            lastname: string;
            email: string;
        }
    };
    civility: string;
    lastname: string;
    firstname: string;
    email: string;
    profil: string;
    label_tel_primary: string;
    tel_primary: string;
    label_tel_secondary: string;
    tel_secondary: string;
    label_tel_tertiary: string;
    tel_tertiary: string;
    consent: string;
    custom_fields: {
        custom_field_api: {
            label: string;
            value: string;
        };
        custom_field_api2: {
            label: string;
            value: string;
        };
    };
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#tag/Contact-prospect (v1.24 in https://evoliz.io/changelog)):
// {
//     "contactid": 8568,
//         "userid": 3780,
//             "prospect": {
//         "prospectid": 9876,
//             "code": "C00123",
//                 "name": "Triiptic",
//                     "contact": {
//             "contactid": 45,
//                 "firstname": "Olivier",
//                     "lastname": "Gasquet",
//                         "email": "contact@triiptic.fr"
//         }
//     },
//     "civility": "Monsieur",
//         "lastname": "Gasquet",
//             "firstname": "Olivier",
//                 "email": "contact@triiptic.fr",
//                     "profil": "CTO",
//                         "label_tel_primary": "Tél bureau",
//                             "tel_primary": "01 46 72 50 04",
//                                 "label_tel_secondary": "Portable",
//                                     "tel_secondary": "+33600000000",
//                                         "label_tel_tertiary": "Télécopie (bureau)",
//                                             "tel_tertiary": "0900000000",
//                                                 "consent": "without",
//                                                     "custom_fields": {
//         "custom_field_api": {
//             "label": "label1",
//                 "value": "value1"
//         },
//         "custom_field_api2": {
//             "label": "label2",
//                 "value": "value2"
//         }
//     }
// }