import IDistantVOBase from "../../../../IDistantVOBase";

export default class ClasseCSSVO implements IDistantVOBase {

    public static API_TYPE_ID: string = "classe_css";

    public id: number;
    public _type: string = ClasseCSSVO.API_TYPE_ID;

    /**
     * Nom de la classe, pour l'affichage
     */
    public name: string;

    /**
     * Nom de la classe CSS telle que déclarée dans le CSS, basé sur le nom + un id ?
     * Est-ce qu'on utilise pas l'id directement dans le CSS ? mais pas très lisible...
     * todo trigger precreate => le nom est figé ensuite tant pis si on s'est trompé de nom au départ...
     * unique évidemment
     */
    public autogenerated_name: string;

    /**
     * Description de la classe, pour expliquer son usage
     */
    public description: string;

    /**
     * Le CSS de la classe, tel qu'il sera utilisé poussé par le générateur et reload au besoin à l'exec
     * Format textarea (mais coloration css donc type dédié)
     */
    public css: string;
}