import IDistantVOBase from "../../../../IDistantVOBase";

export default class ClasseCSSVO implements IDistantVOBase {

    public static API_TYPE_ID: string = "classe_css";

    public id: number;
    public _type: string = ClasseCSSVO.API_TYPE_ID;

    /**
     * Nom de la classe, pour l'affichage
     */
    public name: string;

    /**
     * Nom de la classe CSS telle que déclarée dans le CSS, basé sur le nom + un id ?
     * Est-ce qu'on utilise pas l'id directement dans le CSS ? mais pas très lisible...
     * todo trigger precreate => le nom est figé ensuite tant pis si on s'est trompé de nom au départ...
     * unique évidemment
     */
    public autogenerated_name: string;

    /**
     * Si cette classe CSS est un alias d'une classe codée simplement pour référence,
     *  alors ce css ne doit pas être éditable, et on indique la classe CSS de référence
     * Typiquement pour faire référence aux types de bootstrap
     */
    public is_alias: boolean;
    public css_class_ref_name: string;

    /**
     * Description de la classe, pour expliquer son usage
     */
    public description: string;

    /**
     * Le CSS de la classe, tel qu'il sera utilisé poussé par le générateur et reload au besoin à l'exec
     * Format textarea (mais coloration css donc type dédié)
     */
    public css: string;

    /**
     * Format HTML avec Wysiwig
     * Pour permettre d'afficher un exemple de rendu de la classe CSS
     *  par exemple sur du font-awesome, on peut afficher l'icône :
     * <i class='fa {css_class_name}'></i>
     * ou pour un texte :
     * <p class='{css_class_name}'>Exemple de texte</p>
     * Si on est sur un alias on remplace {css_class_name} par css_class_ref_name, sinon par autogenerated_name
     */
    public html_demo: string;
}