export default interface IEvolizAPICash {
    cashid: number;
    userid: number;
    label: string;
    stampdate: string;
    startdate: string;
    accounting_code: string;
    journal_code: string;
    paytypes: [{
        paytypeid: number;
        label: string;
        automatic: boolean;
        initial_balance: number;
        with_fees: boolean;
        accounting_code: string;
        balance: number;
        enabled: boolean;
        cash_paytype: boolean;
    }];
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Cash-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "cashid": 45,
//         "userid": 3780,
//             "label": "Caisse Toulon",
//                 "stampdate": "2022-01-01T09:26:39.000000Z",
//                     "startdate": "2022-01-01",
//                         "accounting_code": "530",
//                             "journal_code": "CA",
//                                 "paytypes": [
//                                     {
//                                         "paytypeid": 44,
//                                         "label": "Espèce",
//                                         "automatic": false,
//                                         "initial_balance": 2000,
//                                         "with_fees": false,
//                                         "accounting_code": "001",
//                                         "balance": 5774.46,
//                                         "enabled": true,
//                                         "cash_paytype": true
//                                     },
//                                     {
//                                         "paytypeid": 45,
//                                         "label": "Carte bancaire",
//                                         "automatic": true,
//                                         "initial_balance": 0,
//                                         "with_fees": false,
//                                         "accounting_code": "002",
//                                         "balance": 0,
//                                         "enabled": true,
//                                         "cash_paytype": false
//                                     }
//                                 ]
// }