export default interface IEvolizAPIDocumentLinks {
    credits: [{
        id: number;
        link: string;
    }];
    payments: [{
        id: number;
        link: string;
    }];
    advances: [{
        id: number;
        link: string;
    }];
    invoices: [{
        id: number;
        link: string;
    }];
    deliveries: [{
        id: number;
        link: string;
    }];
    sale_orders: [{
        id: number;
        link: string;
    }];
    quotes: [{
        id: number;
        link: string;
    }];
    cashentries: [{
        id: number;
        link: string;
    }];
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Document-links-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "credits": [
//         {
//             "id": 123456,
//             "link": "https://www.evoliz.io/api/companies/X/invoices/123456"
//         }
//     ],
//         "payments": [
//             {
//                 "id": 123456,
//                 "link": "https://www.evoliz.io/api/companies/X/invoices/123456"
//             }
//         ],
//             "advances": [
//                 {
//                     "id": 123456,
//                     "link": "https://www.evoliz.io/api/companies/X/invoices/123456"
//                 }
//             ],
//                 "invoices": [
//                     {
//                         "id": 123456,
//                         "link": "https://www.evoliz.io/api/companies/X/invoices/123456"
//                     }
//                 ],
//                     "deliveries": [
//                         {
//                             "id": 123456,
//                             "link": "https://www.evoliz.io/api/companies/X/invoices/123456"
//                         }
//                     ],
//                         "sale_orders": [
//                             {
//                                 "id": 123456,
//                                 "link": "https://www.evoliz.io/api/companies/X/invoices/123456"
//                             }
//                         ],
//                             "quotes": [
//                                 {
//                                     "id": 123456,
//                                     "link": "https://www.evoliz.io/api/companies/X/invoices/123456"
//                                 }
//                             ],
//                                 "cashentries": [
//                                     {
//                                         "id": 123456,
//                                         "link": "https://www.evoliz.io/api/companies/X/invoices/123456"
//                                     }
//                                 ]
// }