export default interface IEvolizAPIPayment {
    paymentid: number;
    userid: number;
    document: {
        invoiceid: number;
        creditid: number;
        advanceid: number;
        document_number: string;
    };
    cashentry: {
        entryid: number;
        date: string;
        cash: {
            cashid: number;
            label: string;
        }
    };
    paydate: string;
    stampdate: string;
    client: {
        clientid: number;
        code: string;
        name: string;
        civility: string;
        contact: {
            contactid: number;
            firstname: string;
            lastname: string;
            email: string;
        }
    };
    label: string;
    paytype: {
        paytypeid: number;
        paytype: string;
    };
    default_currency: {
        code: string;
        conversion: number;
        symbol: string;
    };
    document_currency: {
        code: string;
        conversion: string;
        symbol: string;
    };
    amount: number;
    currency_amount: any;
    links: string;
    comment: string;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Payment-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "paymentid": 2476128,
//         "userid": 3780,
//             "document": {
//         "invoiceid": 4013943,
//             "creditid": 4013943,
//                 "advanceid": 4013943,
//                     "document_number": "F-20190000160"
//     },
//     "cashentry": {
//         "entryid": 4545,
//             "date": "2022-01-01",
//                 "cash": {
//             "cashid": 45,
//                 "label": "Caisse Toulon"
//         }
//     },
//     "paydate": "2019-10-10",
//         "stampdate": "2019-10-10T09:26:39.000000Z",
//             "client": {
//         "clientid": 9876,
//             "code": "C00123",
//                 "name": "Triiptic",
//                     "civility": "M.",
//                         "contact": {
//             "contactid": 45,
//                 "firstname": "Olivier",
//                     "lastname": "Gasquet",
//                         "email": "contact@triiptic.fr"
//         }
//     },
//     "label": "Règlement client",
//         "paytype": {
//         "paytypeid": 4,
//             "paytype": "Chèque"
//     },
//     "default_currency": {
//         "code": "EUR",
//             "conversion": 1,
//                 "symbol": "€"
//     },
//     "document_currency": {
//         "code": "USD",
//             "conversion": "1,10",
//                 "symbol": "$"
//     },
//     "amount": 537.71,
//         "currency_amount": null,
//             "links": "https://.../links/payment/2476128",
//                 "comment": "Chèque numéro 1234"
// }