export default interface IEvolizAPISaleOrder {
    orderid: number;
    document_number: string;
    userid: number;
    client: {
        clientid: number;
        code: string;
        name: string;
        civility: string;
        contact: {
            contactid: number;
            firstname: string;
            lastname: string;
            email: string;
        }
    };
    default_currency: {
        code: string;
        conversion: number;
        symbol: string;
    };
    document_currency: any;
    total: {
        rebate: {
            amount_vat_exclude: number;
            percent: number;
        };
        vat_exclude: number;
        vat: number;
        vat_include: number;
        margin: {
            purchase_price_vat_exclude: number;
            margin_percent: number;
            markup_percent: number;
            amount: number;
        };
        advance: number;
        paid: number;
        net_to_pay: number;
    };
    currency_total: any;
    status_code: number;
    status: string;
    status_dates: {
        create: string;
        sent: any;
        inpayment: any;
        paid: any;
        match: any;
    };
    locked: boolean;
    lockdate: any;
    object: string;
    documentdate: string;
    duedate: string;
    execdate: string;
    term: {
        penalty: number;
        nopenalty: boolean;
        recovery_indemnity: boolean;
        discount_term: number;
        no_discount_term: boolean;
        payterm: {
            paytermid: number;
            label: string;
        };
        paytype: {
            paytypeid: number;
            label: string;
        };
    };
    comment: string;
    comment_clean: string;
    external_document_number: string;
    enabled: boolean;
    analytic: {
        id: number;
        code: string;
        label: string;
        enabled: boolean;
    };
    file: string;
    links: string;
    webdoc: string;
    template: {
        templateid: number;
        label: string;
    };
    items: [{
        itemid: number;
        articleid: number;
        reference: string;
        reference_clean: string;
        designation: string;
        designation_clean: string;
        quantity: number;
        unit: string;
        unit_price_vat_exclude: number;
        unit_price_vat_exclude_currency: any;
        vat: number;
        total: {
            rebate: any;
            vat_exclude: number;
            vat: number;
            vat_include: number;
            margin: {
                purchase_unit_price_vat_exclude: number;
                coefficient: number;
                margin_percent: number;
                markup_percent: number;
                amount: number;
            };
        };
        currency_total: any;
        sale_classification: {
            id: number;
            code: number;
            label: string;
        };
    }];
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Sale-order-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "orderid": 2476128,
//         "document_number": "F-20190000160",
//             "userid": 3780,
//                 "client": {
//         "clientid": 9876,
//             "code": "C00123",
//                 "name": "Triiptic",
//                     "civility": "M.",
//                         "contact": {
//             "contactid": 45,
//                 "firstname": "Olivier",
//                     "lastname": "Gasquet",
//                         "email": "contact@triiptic.fr"
//         }
//     },
//     "default_currency": {
//         "code": "EUR",
//             "conversion": 1,
//                 "symbol": "€"
//     },
//     "document_currency": null,
//         "total": {
//         "rebate": {
//             "amount_vat_exclude": 36,
//                 "percent": 10
//         },
//         "vat_exclude": 324,
//             "vat": 64.8,
//                 "vat_include": 388.8,
//                     "margin": {
//             "purchase_price_vat_exclude": 16,
//                 "margin_percent": 87.5,
//                     "markup_percent": 46.67,
//                         "amount": 20
//         },
//         "net_to_pay": 0
//     },
//     "currency_total": null,
//         "status_code": 2,
//             "status": "create",
//                 "status_dates": {
//         "create": "2019-10-10T09:26:39.000000Z",
//             "sent": null,
//                 "accept": null,
//                     "wait": null,
//                         "reject": null,
//                             "pack": null,
//                                 "invoice": null,
//                                     "close": "2019-10-10T09:37:12.000000Z"
//     },
//     "object": "Abonnement Logiciel Gestion Commerciale",
//         "documentdate": "2019-10-10",
//             "duedate": "2019-10-25",
//                 "execdate": "2019-09-12",
//                     "delivery_date": null,
//                         "retract": null,
//                             "term": {
//         "penalty": 3,
//             "nopenalty": false,
//                 "recovery_indemnity": false,
//                     "discount_term": 0,
//                         "no_discount_term": false,
//                             "payterm": {
//             "paytermid": 3,
//                 "label": "15 jours"
//         },
//         "paytype": {
//             "paytypeid": 3,
//                 "label": "Carte bancaire"
//         }
//     },
//     "comment": "Titulaire du compte : Hingis160 SARL<br />\nDomiciliation du compte : Boulogne<br />\nIBAN : FR7612345678901234567890123",
//         "comment_clean": "Titulaire du compte : Hingis160 SARL\nDomiciliation du compte : Boulogne\nIBAN : FR7612345678901234567890123",
//             "external_document_number": "EXT001",
//                 "enabled": true,
//                     "analytic": {
//         "id": 12345,
//             "code": "ANA3",
//                 "label": "Axe analytique 3",
//                     "enabled": false
//     },
//     "file": "https://.../files/corder/2476128",
//         "links": "https://.../links/corder/2476128",
//             "webdoc": "https://.../modules/webdoc/5MDKOED5NATQJGE21886-9ccce0c003319d10d2e94af0c75977ed",
//                 "template": {
//         "templateid": 44,
//             "label": "Standard 2"
//     },
//     "items": {
//         "itemid": 12345,
//             "articleid": 12345,
//                 "reference": "SPLIT",
//                     "reference_clean": "SPLIT",
//                         "designation": "Banana Split <br />\nPour une durée de 12 mois",
//                             "designation_clean": "Banana Split\nPour une durée de 12 mois",
//                                 "quantity": 12,
//                                     "unit": "M",
//                                         "unit_price_vat_exclude": 30,
//                                             "unit_price_vat_exclude_currency": null,
//                                                 "vat": 20,
//                                                     "total": {
//             "rebate": null,
//                 "vat_exclude": 360,
//                     "vat": 72,
//                         "vat_include": 432,
//                             "margin": {
//                 "purchase_unit_price_vat_exclude": 16,
//                     "coefficient": 3.6,
//                         "margin_percent": 87.5,
//                             "markup_percent": 46.67,
//                                 "amount": 20
//             }
//         },
//         "currency_total": {
//             "rebate": {
//                 "amount_vat_exclude": 165.36,
//                     "percent": 10
//             },
//             "vat_exclude": 1653.59,
//                 "vat": 330.71,
//                     "vat_include": 1984.3,
//                         "margin": {
//                 "purchase_price_vat_exclude": 16,
//                     "margin_percent": 87.5,
//                         "markup_percent": 46.67,
//                             "amount": 20
//             }
//         },
//         "sale_classification": {
//             "id": 45732,
//                 "code": 4,
//                     "label": "Vente de marchandise"
//         }
//     }
// }