export default interface IEvolizAPIFile {
    file_name: string;
    file_size: number;
    file_content: string;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/File-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "file_name": "H-000000000001.pdf",
//         "file_size": 1552365,
//             "file_content": "base64encodedcontent"
// }