export default interface IEvolizAPIAttachment {
    attachmentid: number;
    doc_type: string;
    docid: number;
    file_name: string;
    file_size: number;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Attachment-resource (v1.24 in https://evoliz.io/changelog)):
// {
//     "attachmentid": 1552,
//         "doc_type": "buy",
//             "docid": 6532,
//                 "file_name": "H-000000000001.pdf",
//                     "file_size": 1552365
// }