export default interface IEvolizAPIUser {
    id: number;
    firstname: string;
    lastname: string;
    profile: string;
    email: string;
    createdate: string;
    lastconnect: string;
    role: string;
    phone: string;
    mobile: string;
    fax: string;
    enabled: boolean;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/User-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "id": 11615,
//         "firstname": "François",
//             "lastname": "Aupetit",
//                 "profile": "user",
//                     "email": "contact@triiptic.fr",
//                         "createdate": "2020-08-16T07:06:18.000000Z",
//                             "lastconnect": "2021-01-15T08:17:44.000000Z",
//                                 "role": "CTO",
//                                     "phone": "01 46 72 50 04",
//                                         "mobile": "+33600000000",
//                                             "fax": "+33400000000",
//                                                 "enabled": true
// }