export default interface IEvolizAPISubscription {
    contract: string;
    type: string;
    duration: string;
    nb_users: number;
    startdate: string;
    enddate: string;
    amount: {
        vat_exclude: number;
        vat_include: number;
    };
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Subscription-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "contract": "COMBO",
//         "type": "COMPANY",
//             "duration": "1 months",
//                 "nb_users": 0,
//                     "startdate": "2020-03-30T18:30:00.000000Z",
//                         "enddate": "2020-04-30T18:30:00.000000Z",
//                             "amount": {
//         "vat_exclude": 40,
//             "vat_include": 48
//     }
// }