export default interface IEvolizAPITemplateMenu {
    template_menuid: number;
    label: string;
    mode: string;
    mode_label: string;
    stampdate: string;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Template-menu-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "template_menuid": 153,
//         "label": "full",
//             "mode": "business",
//                 "mode_label": "Matching document with bank",
//                     "stampdate": "2019-08-24T14:15:22Z"
// }