export default interface IEvolizAPICompany {
    companyid: number;
    company_code: string;
    company_name: string;
    access_path: string;
    email: string;
    phone: string;
    legal_status: {
        legal_status_code: string;
        label: string;
        other_label: string;
    };
    address: {
        addr: string;
        addr2: string;
        postcode: string;
        town: string;
        country: {
            label: string;
            iso2: string;
        };
    };
    home_site: {
        home_siteid: number;
        home_site: string;
    };
    template_menu: {
        template_menuid: number;
        label: string;
        mode: string;
        mode_label: string;
        stampdate: string;
    };
    accounting: {
        beginning_date: string;
        ending_date: string;
    };
    lastconnect: string;
    mode: string;
    live: boolean;
    term: {
        payterm: {
            paytermid: number;
            label: string;
        };
        paytype: {
            paytypeid: number;
            label: string;
        };
    };
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Company-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "companyid": 2,
//         "company_code": "1234",
//             "company_name": "Triiptic",
//                 "access_path": "masociete",
//                     "email": "contact@triiptic.fr",
//                         "phone": "01 46 72 50 04",
//                             "legal_status": {
//         "legal_status_code": "other",
//             "label": "Autre statut juridique",
//                 "other_label": "Fiducie"
//     },
//     "address": {
//         "addr": "176 avenue Joseph Louis Lambot",
//             "addr2": "Etage 2",
//                 "postcode": "83130",
//                     "town": "La Garde",
//                         "country": {
//             "label": "France",
//                 "iso2": "FR"
//         }
//     },
//     "home_site": {
//         "home_siteid": 34,
//             "home_site": "Paris Clisson"
//     },
//     "template_menu": {
//         "template_menuid": 153,
//             "label": "full",
//                 "mode": "business",
//                     "mode_label": "Matching document with bank",
//                         "stampdate": "2019-08-24T14:15:22Z"
//     },
//     "accounting": {
//         "beginning_date": "01-01",
//             "ending_date": "12-31"
//     },
//     "lastconnect": "2019-10-10T09:26:39.000000Z",
//         "mode": "BUSINESS",
//             "live": false,
//                 "term": {
//         "payterm": {
//             "paytermid": 3,
//                 "label": "15 jours"
//         },
//         "paytype": {
//             "paytypeid": 3,
//                 "label": "Carte bancaire"
//         }
//     }
// }