export default interface IEvolizAPITemplateExport {
    template_exportid: number;
    label: string;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Template-export-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "template_exportid": 153,
//         "label": "Outil de production comptable"
// }