export default interface IEvolizAPIBankItem {
    bank_item_id: number;
    label: string;
    date: string;
    amount: number;
    comment: string;
    bank: {
        bankid: number;
        bank_name: string;
    };
    matched: boolean;
    matchdate: string;
    matched_elements: [{
        type: string;
        id: number;
    }];
    locked: boolean;
    lockdate: string;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#tag/Bank-Item (v1.24 in https://evoliz.io/changelog)):
// {
//     "bank_itemid": 5678901,
//         "label": "FACTURE CARTE DU 061119 EVOLIZ SPLIT CARTE 1234XXXXXXXX5678",
//             "date": "2019-11-06",
//                 "amount": -388.8,
//                     "comment": "Abonnement Gestion Commerciale",
//                         "bank": {
//         "bankid": 12345,
//             "bank_name": "Banque Populaire"
//     },
//     "matched": true,
//         "matchdate": "2019-11-11T09:26:39.000000Z",
//             "matched_elements": [
//                 {
//                     "type": "buy",
//                     "id": 2361910
//                 }
//             ],
//                 "locked": true,
//                     "lockdate": "2020-02-14T09:26:39.000000Z"
// }