export default interface IEvolizAPIBankAccount {
    bankid: number;
    label: string;
    account_code: string;
    journal_code: string;
    balance: number;
    balance_date: string;
    enabled: boolean;
}
// Generated by Copilot, using the following code as a prompt (from https://evoliz.io/documentation#section/Bank-resources (v1.24 in https://evoliz.io/changelog)):
// {
//     "bankid": 567,
//         "label": "Banque par défaut",
//             "account-code": "512",
//                 "journal-code": "BQ",
//                     "balance": 345.45,
//                         "balance-date": "2019-01-01",
//                             "enabled": true
// }